* Charla

# Outline

- Quien soy y que hago en Qontigo
  - Qontigo - Axioma - AxR - Core Analytics - APL

- Reporte, UI, Cloud Orquestration, Market Data, RiskEngine, Results, Batch Jobs.

- Refactoring de código de Pricer y creación de componentes/librerías

- DBA, Research, MarketData, RiskModel, DevOps, Devs, Quants,  QuantDevs 

- Integración con Index

##

- que es dev exp


Build - Verificar que los cambios se pueden compilar y están libres de errores de sintaxis.
(Verify that changes are free of syntax error and compile.)
    
Test - (Verificar que todos los tests automáticos pasan)
 Verify that all automated tests pass.
   
Start - Simular una ejecución de E2E en un ambiente deployado (Launch end-to-end to simulate execution in a deployed environment.)
    
Debug - 
Attachear un debugger, setear breakpoints, recorrer el código e inspeccionar variables.

(Attach debugger to started solution, set breakpoints, step through code, and inspect variables.)

Goals

Maximizar el tiempo que lxs Devs dedican a desarrollar código nuevo.

Minimizar el tiempo utilizado en configurar y setup las herramientas de trabajo

Minimizar las regresiones y nuevos defectos al tener un E2E testing sencillo.


Maximize the amount of time engineers spend on writing code that fulfills story acceptance and done-done criteria.

Minimize the amount of time spent manual setup and configuration of tooling

Minimize regressions and new defects by making end-to-end testing easy

###

Cómo egresado de FCyN, fui formado para analizar. Desmembrar

Diseño/Ingeniería -> Síntesis, construir, componer

Imponer rieles, seguridad, guías

Trabajo colaborativo vs Individual



###

- como aplicarlo
  - habilidades del desarrollador
  - protección en las herramientas
  - invalid state irrepresentable
  - Mono repo/polyrepo/monolith/polylith
  - reproducibility/version management
  - automate code review
  - Avoid Average and think in ranges.
  - facilitar guidance, docs
  
- GitHub actions
  - sanity checks
  - build
  - test
  - lint
  - sonarqube
  - summary
- Docs on interaction with other teams
- No bash
- integration tests
- publishing packages / features / report 
- rule of thumb, a la tercera implementarlo.
- habilitar a otros miembros del equipo a
  

